### ISSUE TITLE
priority problem based on MTR

### ISSUE THREAD

**Issue by anthonyhan** [ptrefall/fluid-hierarchical-task-network#8]
**Describe the bug**

Base on the Humphreys' article, MTR with a lower index should have higher priority.

https://github.com/ptrefall/fluid-hierarchical-task-network/blob/de2c39066f34ee5f8d205366c53ce27270b35391/Fluid-HTN/Tasks/CompoundTasks/Selector.cs#L61

**To Reproduce**
For example:
ctx.LastMTR: [0, 3, 0]
ctx.MethodTraversalRecord:  [0, 0]
taskIndex  = 1

**Expected behavior**
[0,0,1] should have a higher priority than [0,3,0].

**Comment by ptrefall** [comment]
Hm, I don't quite see how the code you linked doesn't follow Humphrey's rule here. if LastMTR at current decomposition index has a lower value than the current task index, then [0, **0**, 1] would beat [0, **3**, 0]. 

Note that TaskIndex represent the index from the parent compound task's point of view, so if it has 3 sub-tasks, it will run through taskIndex 0, 1 and 2, and we'll compare LastMTR at that depth of _currentDecompositionIndex_ against that task index. As you can see in Selector line 133, we do: ctx.MethodTraversalRecord.Add(taskIndex); when we have successfully decomposed at that level.

This means that during a replan, we'll never get to [0, 0, **1**] vs [0, 3, **0**], because we already rejected it at [0, **0**, 1] vs [0, **3**, 0].

Does this explanation resolve the bug, or do you have a small test-project that can reproduce it, preferably a simple unit-test, if you still think there is a bug here? We already have a test that passes called DecomposeCompoundSubtaskLoseToLastMTR_ExpectedBehavior(), but maybe it doesn't cover your use-case?

And finally, thank you for submitting the issue!

**Comment by ptrefall** [comment]
Ah, after writing I realized I had misinterpreted what you wrote. So if LastMTR is [0, 3, **0**] and current MTR is [0, 0, **1**], then we should indeed not get rejected, but we are indeed rejected. I wrote a new unit test to reproduce this problem. I'll work on a fix. Thank you again.

```
[TestMethod]
        public void DecomposeCompoundSubtaskWinOverLastMTR_ExpectedBehavior()
        {
            var ctx = new MyContext();
            var rootTask = new Selector() { Name = "Root" };
            var task = new Selector() { Name = "Test1" };
            var task2 = new Selector() { Name = "Test2" };
            var task3 = new Selector() {Name = "Test3"};

            task3.AddSubtask(new PrimitiveTask() { Name = "Sub-task3-1" }.AddCondition(new FuncCondition<MyContext>("Done == true", context => context.Done == true)));
            task3.AddSubtask(new PrimitiveTask() { Name = "Sub-task3-2" });

            task2.AddSubtask(new PrimitiveTask() { Name = "Sub-task2-1" }.AddCondition(new FuncCondition<MyContext>("Done == true", context => context.Done == true)));
            task2.AddSubtask(new PrimitiveTask() { Name = "Sub-task2-2" });

            task.AddSubtask(task2);
            task.AddSubtask(task3);
            task.AddSubtask(new PrimitiveTask() { Name = "Sub-task1-1" }.AddCondition(new FuncCondition<MyContext>("Done == false", context => context.Done == false)));

            rootTask.AddSubtask(task);

            ctx.LastMTR.Add(0);
            ctx.LastMTR.Add(1);
            ctx.LastMTR.Add(0);
            var status = rootTask.Decompose(ctx, 0, out var plan);

            Assert.IsTrue(status == DecompositionStatus.Succeeded);
        }
```

**Comment by ptrefall** [comment]
Please verify @anthonyhan, the bug should now be fixed.

**Comment by anthonyhan** [comment]
@ptrefall  I tested it and the planner works well, Thanks.

**Comment by ptrefall** [comment]
I'm glad to hear it!
